### ISSUE TITLE
Paquetes externos.

### ISSUE THREAD

**Issue by fperezpt** [hbiarge/DnDZgZ.WP7#1]
He encontrado y tratado de instalar los paquetes MVVM de Galasoft (Libraries) con NuGet.  Pero la instalación ha modificado y añadido un montón de cosas en el proyecto (ya lo he revertido en mi workingcopy).

Propongo:
1.- Tratamos de no utilizar paquetes externos al propio VS2010
2.- Haces una guia de instalación (correcta) y uso.... jejejejeje  ;-)

Saludines....

**Comment by hbiarge** [comment]
Cierto.
Fallo mío, porque MVVM Light lo tengo instalado en mi máquina. Por eso no está como paquete NuGet.
Si te parece, lo añado como paquete NuGet para que no haya ninguna dependencia que no esté incluida en el proyecto. Si que me gustaría seguir utilizándolo, porque creo que es un toolkit muy interesante y ligero para trabajar con el paatrón MVVM en WPF/Silverlight/WP7.
Añado también en el ReadMe una pequeña descripción de las ideas sobre las que voy desarrollando.

**Comment by hbiarge** [comment]
Tienes problemas con alguna referencia mas??

**Comment by fperezpt** [comment]
En principio no, creo que era la única.  Pero al hacer la inclusión con NuGet se han modificado tantas cosas que tampoco te lo puedo asegurar al 100%.  Le echo un ojo esta semana.  Al menos que pueda compilar.  Luego ya me meto más a fondo con ello.
Gracias.

**Comment by fperezpt** [comment]
Quizá tenemos que "invertir" un primer día (como con el Kit-AOS) en que me hagas una introducción de MVVM y por donde vamos a tirar, en general.

Ya hablamos.
